<?php

namespace Targeo\ExportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExportRepository extends EntityRepository
{
}
