<?php

namespace Tarsago\ExportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IMRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IMRepository extends EntityRepository
{
    const RI_QUERY = <<<DQL
                SELECT im, COUNT(im.id) as CNTRP from TarsagoExportBundle:IM im
                GROUP BY im.cmpField
                ORDER BY im.dataTrans asc
DQL;
    
    public function getRI(Export $export)
    {
        
        $query = $this->getEntityManager()->createQuery(self::RI_QUERY);
        return $query->getResult();
        
    }
    
}
